# Generated by Django 5.2.6 on 2025-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
