# Generated by Django 5.1.6 on 2025-09-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_cor_categoria_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
